export const ROUTE_NAMES = {
  home: "home",
  signup: "signup",
  login: "login",
  passwordReset: "password-reset",
  passwordResetConfirm: "password-reset-confirm",
  verifyEmail: "verify-email",
  authDebug: "auth-debug",
  projectCreate: "project-create",
  projectDebug: "project-debug",
  projectDashboard: "project-dashboard",
  projectThreads: "project-threads",
  projectMembers: "project-members",
  projectRoles: "project-roles",
  projectCategories: "project-categories",
  projectInvites: "project-invites",
  projectSettings: "project-settings",
  projectActivity: "project-activity",
  projectNotifications: "project-notifications",
  projectTaskDetail: "project-task-detail",
  inviteAccept: "invite-accept",
  myPage: "my-page",
  myTasks: "my-tasks",
  secretAccess: "secret-access",
  secretChat: "secret-chat",
  notFound: "not-found",
  demoDashboard: "demo.dashboard",
} as const;
